import { Place } from "../interface";

export const INDIAN_PLACES: Place[] = [
  {
    id: "1",
    name: "Naini Lake",
    state: "Uttarakhand",
    type: "Natural Attraction",
    description: "A picturesque, crescent-shaped lake surrounded by hills.",
    rating: 4.8,
    famousFor: ["Boating", "Photography", "Peaceful Environment"],
  },
  {
    id: "2",
    name: "Naina Devi Temple",
    state: "Uttarakhand",
    type: "Temple",
    description:
      "A sacred temple located near Naini Lake dedicated to Goddess Naina Devi.",
    rating: 4.7,
    famousFor: ["Spirituality", "Festivals", "Serenity"],
  },
  {
    id: "3",
    name: "Snow View Point",
    state: "Uttarakhand",
    type: "Viewpoint",
    description:
      "A popular spot offering panoramic views of the snow-capped Himalayas.",
    rating: 4.6,
    famousFor: ["Himalayan Views", "Photography", "Cable Car Ride"],
  },
  {
    id: "4",
    name: "Tiffin Top",
    state: "Uttarakhand",
    type: "Viewpoint",
    description:
      "A scenic spot offering breathtaking views of the surrounding hills and Nainital town.",
    rating: 4.5,
    famousFor: ["Trekking", "Photography", "Nature Walks"],
  },
  {
    id: "5",
    name: "Nainital Zoo",
    state: "Uttarakhand",
    type: "Wildlife Sanctuary",
    description:
      "High-altitude zoo home to rare Himalayan species like snow leopards and red pandas.",
    rating: 4.4,
    famousFor: ["Wildlife", "Family Outing", "Education"],
  },
  {
    id: "6",
    name: "Mall Road",
    state: "Uttarakhand",
    type: "Shopping Destination",
    description:
      "A bustling road along Naini Lake lined with shops, eateries, and cafes.",
    rating: 4.3,
    famousFor: ["Shopping", "Local Cuisine", "Evening Strolls"],
  },
  {
    id: "7",
    name: "Bhimtal",
    state: "Uttarakhand",
    type: "Natural Attraction",
    description:
      "A serene lake located near Nainital, famous for its island in the middle.",
    rating: 4.6,
    famousFor: ["Boating", "Peaceful Ambiance", "Aquarium"],
  },
  {
    id: "8",
    name: "St. John in the Wilderness Church",
    state: "Uttarakhand",
    type: "Historical Site",
    description: "An ancient Gothic-style church set amidst a serene forest.",
    rating: 4.5,
    famousFor: ["Architecture", "History", "Peaceful Surroundings"],
  },
  {
    id: "9",
    name: "Kathgodam Railway Station",
    state: "Uttarakhand",
    type: "Transportation Hub",
    description:
      "The nearest railway station to Nainital, serving as a gateway to the region.",
    rating: 4.2,
    famousFor: ["Connectivity", "Convenience", "Travel Hub"],
  },
  {
    id: "10",
    name: "Eco Cave Gardens",
    state: "Uttarakhand",
    type: "Adventure Destination",
    description: "A network of interconnected caves and hanging gardens.",
    rating: 4.4,
    famousFor: ["Caves", "Adventure", "Family Outings"],
  },
];
export const locations = [
  { id: "1", name: "Delhi", country: "India", state: "Delhi" },
  { id: "2", name: "Mumbai", country: "India", state: "Maharashtra" },
  { id: "3", name: "Pune", country: "India", state: "Maharashtra" },
  { id: "4", name: "Kolkata", country: "India", state: "West Bengal" },
  { id: "5", name: "Chennai", country: "India", state: "Tamil Nadu" },
  { id: "6", name: "Bengaluru", country: "India", state: "Karnataka" },
  { id: "7", name: "Hyderabad", country: "India", state: "Telangana" },
  { id: "8", name: "Ahmedabad", country: "India", state: "Gujarat" },
  { id: "9", name: "Jaipur", country: "India", state: "Rajasthan" },
  { id: "10", name: "Lucknow", country: "India", state: "Uttar Pradesh" },
  { id: "11", name: "Bhopal", country: "India", state: "Madhya Pradesh" },
  { id: "12", name: "Chandigarh", country: "India", state: "Punjab/Haryana" },
  { id: "13", name: "Patna", country: "India", state: "Bihar" },
  { id: "14", name: "Thiruvananthapuram", country: "India", state: "Kerala" },
  { id: "15", name: "Guwahati", country: "India", state: "Assam" },
  { id: "16", name: "Shillong", country: "India", state: "Meghalaya" },
  { id: "17", name: "Gangtok", country: "India", state: "Sikkim" },
  { id: "18", name: "Imphal", country: "India", state: "Manipur" },
  { id: "19", name: "Panaji", country: "India", state: "Goa" },
  { id: "20", name: "Shimla", country: "India", state: "Himachal Pradesh" },
  { id: "21", name: "Dehradun", country: "India", state: "Uttarakhand" },
];
